const emailData = [
  {
    from: "Alice Johnson <alice@example.com>",
    to: "bob@example.com",
    subject: "Meeting Reminder",
    body: "Hi Bob,\n\nJust a reminder about our meeting tomorrow at 10 AM. Please make sure to bring the project report and any other relevant documents. Looking forward to our discussion.\n\nBest,\nAlice",
    date: "2024-09-21T10:00:00Z",
    cc: [],
    bcc: [],
    attachments: [],
    isRead: false,
    priority: "normal",
  },
  {
    from: "Carol Smith <carol@example.com>",
    to: "dave@example.com",
    subject: "Project Update",
    body: "Hi Dave,\n\nThe project is on track and we should be able to meet the deadline. The team has been working hard and we have made significant progress. Let's catch up next week to review the milestones.\n\nBest,\nCarol",
    date: "2024-09-15T14:30:00Z",
    cc: [],
    bcc: [],
    attachments: [],
    isRead: true,
    priority: "high",
  },
  {
    from: "Eve Davis <eve@example.com>",
    to: "frank@example.com",
    subject: "Lunch Plans",
    body: "Hi Frank,\n\nAre you free for lunch tomorrow? I found a new restaurant downtown that has great reviews. Let me know if you're interested and we can make a reservation.\n\nBest,\nEve",
    date: "2024-09-20T12:00:00Z",
    cc: [],
    bcc: [],
    attachments: [],
    isRead: false,
    priority: "normal",
  },
  {
    from: "Grace Lee <grace@example.com>",
    to: "heidi@example.com",
    subject: "Conference Invitation",
    body: "Hi Heidi,\n\nYou are invited to speak at our annual conference next month. We believe your expertise would be invaluable to our attendees. Please let us know if you are available and we can discuss the details.\n\nBest,\nGrace",
    date: "2024-08-15T09:00:00Z",
    cc: [],
    bcc: [],
    attachments: [],
    isRead: true,
    priority: "normal",
  },
  {
    from: "Ivan Brown <ivan@example.com>",
    to: "judy@example.com",
    subject: "Job Opportunity",
    body: "Hi Judy,\n\nWe have an exciting job opportunity that matches your skills. The position is for a senior developer role in our company. If you are interested, please send us your updated resume and we can schedule an interview.\n\nBest,\nIvan",
    date: "2024-07-10T16:00:00Z",
    cc: [],
    bcc: [],
    attachments: [],
    isRead: false,
    priority: "high",
  },
  {
    from: "Mallory Wilson <mallory@example.com>",
    to: "oscar@example.com",
    subject: "Code Review",
    body: "Hi Oscar,\n\nCan you please review the latest code changes? We have made some significant updates and your feedback would be greatly appreciated. Let me know if you have any questions.\n\nBest,\nMallory",
    date: "2024-06-05T11:00:00Z",
    cc: [],
    bcc: [],
    attachments: [],
    isRead: true,
    priority: "normal",
  },
  {
    from: "Peggy Martinez <peggy@example.com>",
    to: "trent@example.com",
    subject: "Birthday Party",
    body: "Hi Trent,\n\nYou are invited to my birthday party this weekend. It will be a fun gathering with friends and family. Please let me know if you can make it.\n\nBest,\nPeggy",
    date: "2024-05-01T18:00:00Z",
    cc: [],
    bcc: [],
    attachments: [],
    isRead: false,
    priority: "low",
  },
  {
    from: "Victor Anderson <victor@example.com>",
    to: "walter@example.com",
    subject: "Travel Plans",
    body: "Hi Walter,\n\nLet's discuss our travel plans for the upcoming trip. We need to finalize the itinerary and make the necessary bookings. Looking forward to our adventure.\n\nBest,\nVictor",
    date: "2024-04-28T15:00:00Z",
    cc: [],
    bcc: [],
    attachments: [],
    isRead: true,
    priority: "normal",
  },
  {
    from: "Sybil Thomas <sybil@example.com>",
    to: "trent@example.com",
    subject: "Workshop Details",
    body: "Hi Trent,\n\nHere are the details for the upcoming workshop. Please review the agenda and let me know if you have any questions or suggestions.\n\nBest,\nSybil",
    date: "2024-03-20T13:00:00Z",
    cc: [],
    bcc: [],
    attachments: [],
    isRead: false,
    priority: "normal",
  },
  {
    from: "Wendy Taylor <wendy@example.com>",
    to: "xander@example.com",
    subject: "New Project",
    body: "Hi Xander,\n\nWe are starting a new project and would like you to be a part of it. Your expertise and experience would be a great asset to the team. Let's discuss the details in our next meeting.\n\nBest,\nWendy",
    date: "2024-02-15T10:30:00Z",
    cc: [],
    bcc: [],
    attachments: [],
    isRead: true,
    priority: "high",
  },
  {
    from: "Yvonne Clark <yvonne@example.com>",
    to: "zach@example.com",
    subject: "Team Outing",
    body: "Hi Zach,\n\nWe are planning a team outing next month. It will be a great opportunity for everyone to relax and bond. Please let me know if you have any suggestions for the venue.\n\nBest,\nYvonne",
    date: "2024-01-10T09:00:00Z",
    cc: [],
    bcc: [],
    attachments: [],
    isRead: false,
    priority: "normal",
  },
  {
    from: "Brian Adams <brian@example.com>",
    to: "chris@example.com",
    subject: "Budget Report",
    body: "Hi Chris,\n\nPlease find attached the budget report for the last quarter. Let me know if you have any questions or need any further information.\n\nBest,\nBrian",
    date: "2023-12-05T14:00:00Z",
    cc: [],
    bcc: [],
    attachments: [],
    isRead: true,
    priority: "high",
  },
  {
    from: "Diana Evans <diana@example.com>",
    to: "edward@example.com",
    subject: "Client Meeting",
    body: "Hi Edward,\n\nWe have a client meeting scheduled for next week. Please prepare the presentation and any other necessary documents. Let's ensure we are well-prepared.\n\nBest,\nDiana",
    date: "2023-11-20T11:00:00Z",
    cc: [],
    bcc: [],
    attachments: [],
    isRead: false,
    priority: "normal",
  },
  {
    from: "Fiona Green <fiona@example.com>",
    to: "george@example.com",
    subject: "Holiday Plans",
    body: "Hi George,\n\nWhat are your plans for the holidays? I was thinking of organizing a small get-together with friends. Let me know if you're interested.\n\nBest,\nFiona",
    date: "2023-10-15T16:00:00Z",
    cc: [],
    bcc: [],
    attachments: [],
    isRead: true,
    priority: "low",
  },
  {
    from: "Hannah White <hannah@example.com>",
    to: "ian@example.com",
    subject: "Training Session",
    body: "Hi Ian,\n\nWe have a training session scheduled for next week. Please make sure to complete the pre-training materials and be prepared for the session.\n\nBest,\nHannah",
    date: "2023-09-22T09:00:00Z",
    cc: [],
    bcc: [],
    attachments: [],
    isRead: false,
    priority: "normal",
  },
  {
    from: "Jack Brown <jack@example.com>",
    to: "karen@example.com",
    subject: "Sales Report",
    body: "Hi Karen,\n\nPlease find attached the sales report for the last quarter. Let me know if you have any questions or need any further information.\n\nBest,\nJack",
    date: "2023-08-10T14:00:00Z",
    cc: [],
    bcc: [],
    attachments: [],
    isRead: true,
    priority: "high",
  },
  {
    from: "Laura King <laura@example.com>",
    to: "mike@example.com",
    subject: "Team Meeting",
    body: "Hi Mike,\n\nWe have a team meeting scheduled for tomorrow. Please make sure to bring your updates and any other relevant documents. Looking forward to our discussion.\n\nBest,\nLaura",
    date: "2023-07-05T10:00:00Z",
    cc: [],
    bcc: [],
    attachments: [],
    isRead: false,
    priority: "normal",
  },
  {
    from: "Nancy Scott <nancy@example.com>",
    to: "oliver@example.com",
    subject: "Project Proposal",
    body: "Hi Oliver,\n\nPlease review the attached project proposal and let me know your thoughts. We need to finalize the details before presenting it to the client.\n\nBest,\nNancy",
    date: "2023-06-20T13:00:00Z",
    cc: [],
    bcc: [],
    attachments: [],
    isRead: true,
    priority: "normal",
  },
  {
    from: "Paul Harris <paul@example.com>",
    to: "quincy@example.com",
    subject: "Marketing Strategy",
    body: "Hi Quincy,\n\nWe need to discuss our marketing strategy for the upcoming quarter. Please review the attached document and let me know your availability for a meeting.\n\nBest,\nPaul",
    date: "2023-05-15T11:00:00Z",
    cc: [],
    bcc: [],
    attachments: [],
    isRead: false,
    priority: "high",
  },
  {
    from: "Rachel Turner <rachel@example.com>",
    to: "steve@example.com",
    subject: "Event Planning",
    body: "Hi Steve,\n\nWe need to start planning for the upcoming event. Please review the attached document and let me know your thoughts. Let's schedule a meeting to discuss the details.\n\nBest,\nRachel",
    date: "2023-04-10T16:00:00Z",
    cc: [],
    bcc: [],
    attachments: [],
    isRead: true,
    priority: "normal",
  },
  {
    from: "Tom Wilson <tom@example.com>",
    to: "ursula@example.com",
    subject: "Website Redesign",
    body: "Hi Ursula,\n\nWe need to discuss the website redesign project. Please review the attached document and let me know your availability for a meeting.\n\nBest,\nTom",
    date: "2023-03-05T09:00:00Z",
    cc: [],
    bcc: [],
    attachments: [],
    isRead: false,
    priority: "normal",
  },
  {
    from: "Vera Young <vera@example.com>",
    to: "will@example.com",
    subject: "Product Launch",
    body: "Hi Will,\n\nWe need to finalize the details for the product launch. Please review the attached document and let me know your thoughts. Let's schedule a meeting to discuss the details.\n\nBest,\nVera",
    date: "2023-02-20T14:00:00Z",
    cc: [],
    bcc: [],
    attachments: [],
    isRead: true,
    priority: "high",
  },
  {
    from: "Xena Brown <xena@example.com>",
    to: "yuri@example.com",
    subject: "Budget Planning",
    body: "Hi Yuri,\n\nWe need to start planning the budget for the next fiscal year. Please review the attached document and let me know your availability for a meeting.\n\nBest,\nXena",
    date: "2023-01-15T11:00:00Z",
    cc: [],
    bcc: [],
    attachments: [],
    isRead: false,
    priority: "normal",
  },
  {
    from: "Zara Clark <zara@example.com>",
    to: "adam@example.com",
    subject: "Performance Review",
    body: "Hi Adam,\n\nWe need to schedule your performance review for next week. Please let me know your availability and we can set up a meeting.\n\nBest,\nZara",
    date: "2022-12-10T16:00:00Z",
    cc: [],
    bcc: [],
    attachments: [],
    isRead: true,
    priority: "normal",
  },
];

export default emailData;

export type EmailData = typeof emailData;
export type Email = EmailData[0];
