export const employees = [
  {
    id: "EMP-001",
    firstName: "Shayla",
    lastName: "Coombs",
    email: "shayla.c@cpafirm.com",
    phone: "(555) 123-4567",
    title: "Senior Accountant",
    department: "Tax",
    status: "active",
    hireDate: "2022-03-15",
    terminationDate: null,
    payRate: 85000,
    billRate: 175,
    certifications: ["CPA", "CFE"],
    clients: ["1", "4", "12"],
    projects: ["PRJ-001", "PRJ-004"],
    tasks: ["TASK-001", "TASK-002"],
    supervisor: "EMP-015",
    utilization: 85,
    skills: ["Tax Planning", "Audit", "Financial Analysis"],
    performanceRating: 4.5,
    billableHoursTarget: 1800,
    currentBillableHours: 1350,
    profilePicture: "/avatars/shayla-coombs.jpg",
    office: "Boston",
    remoteStatus: "hybrid",
    emergencyContact: {
      name: "Bob Johnson",
      relationship: "Spouse",
      phone: "(555) 999-8888",
    },
    benefits: {
      healthPlan: "Premium PPO",
      dentalPlan: "Standard",
      visionPlan: "Enhanced",
      "401kParticipation": true,
    },
  },
  {
    id: "EMP-002",
    firstName: "Joshua",
    lastName: "Duncan",
    email: "joshua.d@cpafirm.com",
    phone: "(555) 234-5678",
    title: "Tax Accountant",
    department: "Tax",
    status: "active",
    hireDate: "2023-06-01",
    terminationDate: null,
    payRate: 75000,
    billRate: 150,
    certifications: ["CPA"],
    clients: ["2", "5", "8"],
    projects: ["PRJ-002", "PRJ-003"],
    tasks: ["TASK-003", "TASK-004"],
    supervisor: "EMP-015",
    utilization: 80,
    skills: ["Tax Preparation", "Corporate Tax", "Bookkeeping"],
    performanceRating: 4.0,
    billableHoursTarget: 1800,
    currentBillableHours: 1200,
    profilePicture: "/avatars/joshua-duncan.jpg",
    office: "Boston",
    remoteStatus: "office",
    emergencyContact: {
      name: "Sarah Duncan",
      relationship: "Spouse",
      phone: "(555) 777-6666",
    },
    benefits: {
      healthPlan: "Standard PPO",
      dentalPlan: "Standard",
      visionPlan: "Basic",
      "401kParticipation": true,
    },
  },
];

export type EmployeeData = (typeof employees)[number];
