import type { Individual } from "~/types/types";
import { employees } from "./employeeData";

// Helper function to find employee by ID
const findEmployee = (id: string) => employees.find((emp) => emp.id === id);

export const individuals: Individual[] = [
  {
    id: "1",
    firstName: "John",
    lastName: "Smith",
    email: "john.smith@email.com",
    phone: "(555) 123-4567",
    address: "123 Main St, Boston, MA 02108",
    notes: "Key decision maker for enterprise accounts",
    priority: "High",
    organization: "Tech Corp Inc",
    archived: false,
    profilePicture: "/avatars/john-smith.jpg",
    createdAt: "2023-01-15",
    pointOfContact: findEmployee("EMP-001")!,
  },
  {
    id: "2",
    firstName: "Sarah",
    lastName: "Johnson",
    email: "sarah.j@email.com",
    phone: "(555) 234-5678",
    address: "456 Oak Ave, San Francisco, CA 94105",
    notes: "Prefers email communication",
    priority: "Medium",
    organization: "Digital Solutions LLC",
    archived: false,
    profilePicture: "/avatars/sarah-johnson.jpg",
    createdAt: "2023-02-01",
    pointOfContact: findEmployee("EMP-002")!,
  },
  {
    id: "3",
    firstName: "Michael",
    lastName: "Williams",
    email: "m.williams@email.com",
    phone: "(555) 345-6789",
    address: "789 Pine Rd, Chicago, IL 60601",
    notes: "Monthly check-in scheduled",
    priority: "Low",
    organization: "Innovation Labs",
    archived: false,
    profilePicture: "/avatars/michael-williams.jpg",
    createdAt: "2023-02-15",
    pointOfContact: findEmployee("EMP-001")!,
  },
  {
    id: "4",
    firstName: "Emily",
    lastName: "Brown",
    email: "emily.brown@email.com",
    phone: "(555) 456-7890",
    address: "321 Elm St, Seattle, WA 98101",
    notes: "New client - onboarding in progress",
    priority: "High",
    organization: "Tech Corp Inc",
    archived: false,
    profilePicture: "/avatars/emily-brown.jpg",
    createdAt: "2023-03-01",
    pointOfContact: findEmployee("EMP-002")!,
  },
  {
    id: "5",
    firstName: "David",
    lastName: "Miller",
    email: "david.m@email.com",
    phone: "(555) 567-8901",
    address: "654 Maple Dr, Austin, TX 78701",
    notes: "Interested in premium features",
    priority: "Medium",
    organization: "StartUp Ventures",
    archived: false,
    profilePicture: "/avatars/david-miller.jpg",
    createdAt: "2023-03-15",
    pointOfContact: findEmployee("EMP-001")!,
  },
  {
    id: "6",
    firstName: "Lisa",
    lastName: "Davis",
    email: "lisa.davis@email.com",
    phone: "(555) 678-9012",
    address: "987 Cedar Ln, Denver, CO 80202",
    notes: "Quarterly review pending",
    priority: "High",
    organization: "Growth Co",
    archived: false,
    profilePicture: "/avatars/lisa-davis.jpg",
    createdAt: "2023-04-01",
    pointOfContact: findEmployee("EMP-002")!,
  },
  {
    id: "7",
    firstName: "James",
    lastName: "Wilson",
    email: "j.wilson@email.com",
    phone: "(555) 789-0123",
    address: "741 Birch St, Portland, OR 97201",
    notes: "Contract renewal in 3 months",
    priority: "Medium",
    organization: "Tech Corp Inc",
    archived: true,
    profilePicture: "/avatars/james-wilson.jpg",
    createdAt: "2023-04-15",
    pointOfContact: findEmployee("EMP-001")!,
  },
  {
    id: "8",
    firstName: "Jessica",
    lastName: "Anderson",
    email: "jessica.a@email.com",
    phone: "(555) 890-1234",
    address: "852 Spruce Ave, Miami, FL 33101",
    notes: "Potential upsell opportunity",
    priority: "Low",
    organization: "Digital Solutions LLC",
    archived: false,
    profilePicture: "/avatars/jessica-anderson.jpg",
    createdAt: "2023-05-01",
    pointOfContact: findEmployee("EMP-002")!,
  },
  {
    id: "9",
    firstName: "Robert",
    lastName: "Taylor",
    email: "rob.taylor@email.com",
    phone: "(555) 901-2345",
    address: "963 Willow Rd, Nashville, TN 37201",
    notes: "Requires technical support",
    priority: "High",
    organization: "Innovation Labs",
    archived: false,
    profilePicture: "/avatars/robert-taylor.jpg",
    createdAt: "2023-05-15",
    pointOfContact: findEmployee("EMP-001")!,
  },
  {
    id: "10",
    firstName: "Amanda",
    lastName: "Thomas",
    email: "a.thomas@email.com",
    phone: "(555) 012-3456",
    address: "159 Oak St, Las Vegas, NV 89101",
    notes: "Beta program participant",
    priority: "Medium",
    organization: "StartUp Ventures",
    archived: false,
    profilePicture: "/avatars/amanda-thomas.jpg",
    createdAt: "2023-06-01",
    pointOfContact: findEmployee("EMP-002")!,
  },
  {
    id: "11",
    firstName: "Christopher",
    lastName: "Martinez",
    email: "c.martinez@email.com",
    phone: "(555) 234-5678",
    address: "753 Pine St, Phoenix, AZ 85001",
    notes: "International client",
    priority: "High",
    organization: "Global Tech",
    archived: false,
    profilePicture: "/avatars/chris-martinez.jpg",
    createdAt: "2023-06-15",
    pointOfContact: findEmployee("EMP-001")!,
  },
  {
    id: "12",
    firstName: "Michelle",
    lastName: "Garcia",
    email: "m.garcia@email.com",
    phone: "(555) 345-6789",
    address: "951 Elm Ave, Philadelphia, PA 19101",
    notes: "Needs follow-up",
    priority: "Low",
    organization: "Tech Corp Inc",
    archived: true,
    profilePicture: "/avatars/michelle-garcia.jpg",
    createdAt: "2023-07-01",
    pointOfContact: findEmployee("EMP-002")!,
  },
  {
    id: "13",
    firstName: "Daniel",
    lastName: "Lee",
    email: "daniel.lee@email.com",
    phone: "(555) 456-7890",
    address: "357 Maple St, Houston, TX 77001",
    notes: "VIP client",
    priority: "High",
    organization: "Innovation Labs",
    archived: false,
    profilePicture: "/avatars/daniel-lee.jpg",
    createdAt: "2023-07-15",
    pointOfContact: findEmployee("EMP-001")!,
  },
  {
    id: "14",
    firstName: "Rachel",
    lastName: "Clark",
    email: "r.clark@email.com",
    phone: "(555) 567-8901",
    address: "246 Cedar Dr, Atlanta, GA 30301",
    notes: "New project discussion",
    priority: "Medium",
    organization: "Digital Solutions LLC",
    archived: false,
    profilePicture: "/avatars/rachel-clark.jpg",
    createdAt: "2023-08-01",
    pointOfContact: findEmployee("EMP-002")!,
  },
  {
    id: "15",
    firstName: "Kevin",
    lastName: "Rodriguez",
    email: "k.rodriguez@email.com",
    phone: "(555) 678-9012",
    address: "135 Birch Ln, San Diego, CA 92101",
    notes: "Scaling discussion needed",
    priority: "High",
    organization: "Growth Co",
    archived: false,
    profilePicture: "/avatars/kevin-rodriguez.jpg",
    createdAt: "2023-08-15",
    pointOfContact: findEmployee("EMP-001")!,
  },
  {
    id: "16",
    firstName: "Jennifer",
    lastName: "Lewis",
    email: "jen.lewis@email.com",
    phone: "(555) 789-0123",
    address: "864 Spruce St, Detroit, MI 48201",
    notes: "Partnership opportunity",
    priority: "Medium",
    organization: "Tech Corp Inc",
    archived: false,
    profilePicture: "/avatars/jennifer-lewis.jpg",
    createdAt: "2023-09-01",
    pointOfContact: findEmployee("EMP-002")!,
  },
  {
    id: "17",
    firstName: "William",
    lastName: "Walker",
    email: "w.walker@email.com",
    phone: "(555) 890-1234",
    address: "753 Willow Ave, Minneapolis, MN 55401",
    notes: "Requires monthly reporting",
    priority: "Low",
    organization: "StartUp Ventures",
    archived: false,
    profilePicture: "/avatars/william-walker.jpg",
    createdAt: "2023-09-15",
    pointOfContact: findEmployee("EMP-001")!,
  },
  {
    id: "18",
    firstName: "Elizabeth",
    lastName: "Hall",
    email: "e.hall@email.com",
    phone: "(555) 901-2345",
    address: "951 Oak Rd, Salt Lake City, UT 84101",
    notes: "Integration pending",
    priority: "High",
    organization: "Digital Solutions LLC",
    archived: false,
    profilePicture: "/avatars/elizabeth-hall.jpg",
    createdAt: "2023-10-01",
    pointOfContact: findEmployee("EMP-002")!,
  },
  {
    id: "19",
    firstName: "Andrew",
    lastName: "Young",
    email: "a.young@email.com",
    phone: "(555) 012-3456",
    address: "357 Pine Ave, Sacramento, CA 95801",
    notes: "Security clearance required",
    priority: "Medium",
    organization: "Tech Corp Inc",
    archived: true,
    profilePicture: "/avatars/andrew-young.jpg",
    createdAt: "2023-10-15",
    pointOfContact: findEmployee("EMP-001")!,
  },
  {
    id: "20",
    firstName: "Maria",
    lastName: "King",
    email: "m.king@email.com",
    phone: "(555) 123-4567",
    address: "159 Elm Dr, Charlotte, NC 28201",
    notes: "Expansion plans discussion",
    priority: "High",
    organization: "Growth Co",
    archived: false,
    profilePicture: "/avatars/maria-king.jpg",
    createdAt: "2023-11-01",
    pointOfContact: findEmployee("EMP-002")!,
  },
  {
    id: "21",
    firstName: "Thomas",
    lastName: "Scott",
    email: "t.scott@email.com",
    phone: "(555) 234-5678",
    address: "753 Cedar St, Indianapolis, IN 46201",
    notes: "Annual review scheduled",
    priority: "Low",
    organization: "Innovation Labs",
    archived: false,
    profilePicture: "/avatars/thomas-scott.jpg",
    createdAt: "2023-11-15",
    pointOfContact: findEmployee("EMP-001")!,
  },
  {
    id: "22",
    firstName: "Sandra",
    lastName: "Adams",
    email: "s.adams@email.com",
    phone: "(555) 345-6789",
    address: "951 Maple Ln, Columbus, OH 43201",
    notes: "Product feedback pending",
    priority: "Medium",
    organization: "Digital Solutions LLC",
    archived: false,
    profilePicture: "/avatars/sandra-adams.jpg",
    createdAt: "2023-12-01",
    pointOfContact: findEmployee("EMP-002")!,
  },
  {
    id: "23",
    firstName: "Joseph",
    lastName: "Nelson",
    email: "j.nelson@email.com",
    phone: "(555) 456-7890",
    address: "357 Birch Ave, Pittsburgh, PA 15201",
    notes: "Pilot program participant",
    priority: "High",
    organization: "Tech Corp Inc",
    archived: false,
    profilePicture: "/avatars/joseph-nelson.jpg",
    createdAt: "2023-12-15",
    pointOfContact: findEmployee("EMP-001")!,
  },
  {
    id: "24",
    firstName: "Laura",
    lastName: "Carter",
    email: "l.carter@email.com",
    phone: "(555) 567-8901",
    address: "159 Spruce Dr, Kansas City, MO 64101",
    notes: "Reference client",
    priority: "Medium",
    organization: "StartUp Ventures",
    archived: false,
    profilePicture: "/avatars/laura-carter.jpg",
    createdAt: "2024-01-01",
    pointOfContact: findEmployee("EMP-002")!,
  },
  {
    id: "25",
    firstName: "Steven",
    lastName: "Mitchell",
    email: "s.mitchell@email.com",
    phone: "(555) 678-9012",
    address: "753 Willow Dr, Cleveland, OH 44101",
    notes: "Strategic partnership discussion",
    priority: "High",
    organization: "Growth Co",
    archived: false,
    profilePicture: "/avatars/steven-mitchell.jpg",
    createdAt: "2024-01-15",
    pointOfContact: findEmployee("EMP-001")!,
  },
];

export type IndividualData = (typeof individuals)[number];
