import type { Organization } from "~/types/types";
import { individuals } from "./individualsData";
import { employees } from "./employeeData";

// Helper function to find employee by ID
const findEmployee = (id: string) => employees.find((emp) => emp.id === id);

export const organizations: Organization[] = [
  {
    id: "COMP-001",
    name: "Tech Corp Inc",
    email: "contact@techcorp.com",
    phone: "(555) 111-0000",
    address: "100 Technology Drive, Boston, MA 02108",
    notes: "Enterprise technology solutions provider",
    members: individuals.filter((i) => i.organization === "Tech Corp Inc"),
    archived: false,
    logo: "/logos/techcorp.png",
    priority: "High",
    website: "www.techcorp.com",
    pointOfContact: findEmployee("EMP-001")!,
    createdAt: "2023-01-01",
  },
  {
    id: "COMP-002",
    name: "Digital Solutions LLC",
    email: "info@digitalsolutions.com",
    phone: "(555) 222-0000",
    address: "200 Innovation Way, San Francisco, CA 94105",
    notes: "Digital transformation consultancy",
    members: individuals.filter(
      (i) => i.organization === "Digital Solutions LLC",
    ),
    archived: false,
    logo: "/logos/digitalsolutions.png",
    priority: "Medium",
    website: "www.digitalsolutions.com",
    pointOfContact: findEmployee("EMP-002")!,
    createdAt: "2023-01-02",
  },
  {
    id: "COMP-003",
    name: "Innovation Labs",
    email: "hello@innovationlabs.com",
    phone: "(555) 333-0000",
    address: "300 Research Park, Chicago, IL 60601",
    notes: "R&D and innovation center",
    members: individuals.filter((i) => i.organization === "Innovation Labs"),
    archived: false,
    logo: "/logos/innovationlabs.png",
    priority: "High",
    website: "www.innovationlabs.com",
    pointOfContact: findEmployee("EMP-001")!,
    createdAt: "2023-01-03",
  },
  {
    id: "COMP-004",
    name: "StartUp Ventures",
    email: "contact@startupventures.com",
    phone: "(555) 444-0000",
    address: "400 Startup Lane, Austin, TX 78701",
    notes: "Early stage startup incubator",
    members: individuals.filter((i) => i.organization === "StartUp Ventures"),
    archived: false,
    logo: "/logos/startupventures.png",
    priority: "Medium",
    website: "www.startupventures.com",
    pointOfContact: findEmployee("EMP-002")!,
    createdAt: "2023-01-04",
  },
  {
    id: "COMP-005",
    name: "Global Tech",
    email: "info@globaltech.com",
    phone: "(555) 555-0000",
    address: "500 Global Plaza, New York, NY 10001",
    notes: "International technology firm",
    members: individuals.filter((i) => i.organization === "Global Tech"),
    archived: false,
    logo: "/logos/globaltech.png",
    priority: "High",
    website: "www.globaltech.com",
    pointOfContact: findEmployee("EMP-001")!,
    createdAt: "2023-01-05",
  },
  {
    id: "COMP-006",
    name: "Growth Co",
    email: "hello@growthco.com",
    phone: "(555) 666-0000",
    address: "600 Growth Street, Cleveland, OH 44101",
    notes: "Business growth consultancy",
    members: individuals.filter((i) => i.organization === "Growth Co"),
    archived: false,
    logo: "/logos/growthco.png",
    priority: "Medium",
    website: "www.growthco.com",
    pointOfContact: findEmployee("EMP-002")!,
    createdAt: "2023-01-06",
  },
];

export type OrganizationData = (typeof organizations)[number];
