export const taskData = [
  {
    id: "TASK-001",
    title: "Update Client Portal UI",
    companyName: "TechCorp Solutions",
    projectName: "Client Portal Redesign",
    timeSpent: 12.5,
    timeBudget: 20,
    priority: "high",
    snoozed: false,
    dueDate: "2024-11-25",
    assignee: "Sarah Chen",
    taskCreator: "Michael Rodriguez",
    assignedDate: "2024-11-15",
    attachments: [
      {
        type: "design",
        url: "https://storage.company.com/designs/portal-v2.fig",
        name: "Portal Design V2",
      },
    ],
    archived: false,
    subtasks: [
      {
        id: "ST-001",
        title: "Redesign login page",
        completed: true,
      },
      {
        id: "ST-002",
        title: "Implement new dashboard widgets",
        completed: false,
      },
    ],
  },
  {
    id: "TASK-002",
    title: "Quarterly Financial Report Review",
    companyName: "Global Finance Inc",
    projectName: "Q4 Financial Reporting",
    timeSpent: 4,
    timeBudget: 8,
    priority: "high",
    snoozed: false,
    dueDate: "2024-11-30",
    assignee: "David Wilson",
    taskCreator: "Jennifer Park",
    assignedDate: "2024-11-10",
    attachments: [
      {
        type: "spreadsheet",
        url: "https://storage.company.com/finance/q4-report.xlsx",
        name: "Q4 2024 Report Draft",
      },
    ],
    archived: false,
    subtasks: [
      {
        id: "ST-003",
        title: "Review Q4 projections",
        completed: false,
      },
    ],
  },
  {
    id: "TASK-003",
    title: "Office Supply Inventory",
    companyName: "TechCorp Solutions",
    projectName: "Office Management",
    timeSpent: 1.5,
    timeBudget: 2,
    priority: "low",
    snoozed: true,
    dueDate: null,
    assignee: "Alex Thompson",
    taskCreator: "Sarah Chen",
    assignedDate: null,
    attachments: [],
    archived: false,
    subtasks: [],
  },
  {
    id: "TASK-004",
    title: "Security Audit Implementation",
    companyName: "CyberSafe Systems",
    projectName: "Annual Security Review",
    timeSpent: 28,
    timeBudget: 40,
    priority: "high",
    snoozed: false,
    dueDate: "2024-12-15",
    assignee: "James Kumar",
    taskCreator: "Lisa Chen",
    assignedDate: "2024-11-01",
    attachments: [
      {
        type: "document",
        url: "https://storage.company.com/security/audit-2024.pdf",
        name: "Security Audit Report",
      },
    ],
    archived: false,
    subtasks: [
      {
        id: "ST-004",
        title: "Firewall configuration review",
        completed: true,
      },
      {
        id: "ST-005",
        title: "Update security protocols",
        completed: false,
      },
    ],
  },
  {
    id: "TASK-005",
    title: "Employee Onboarding Documentation",
    companyName: "HR Solutions Pro",
    projectName: "HR Process Improvement",
    timeSpent: 0,
    timeBudget: 10,
    priority: "medium",
    snoozed: false,
    dueDate: "2024-12-01",
    assignee: "Maria Garcia",
    taskCreator: "Robert Kim",
    assignedDate: null,
    attachments: [],
    archived: false,
    subtasks: [],
  },
  {
    id: "TASK-006",
    title: "Legacy System Migration",
    companyName: "TechCorp Solutions",
    projectName: "System Modernization",
    timeSpent: 45,
    timeBudget: 100,
    priority: "medium",
    snoozed: false,
    dueDate: "2025-01-15",
    assignee: "Chris Peterson",
    taskCreator: "Michael Rodriguez",
    assignedDate: "2024-10-15",
    attachments: [
      {
        type: "document",
        url: "https://storage.company.com/projects/migration-plan.pdf",
        name: "Migration Plan",
      },
    ],
    archived: false,
    subtasks: [
      {
        id: "ST-006",
        title: "Data mapping documentation",
        completed: true,
      },
      {
        id: "ST-007",
        title: "Test migration scripts",
        completed: false,
      },
    ],
  },
  {
    id: "TASK-007",
    title: "Marketing Campaign Analysis",
    companyName: "Digital Marketing Pro",
    projectName: "Q4 Campaign Review",
    timeSpent: 8,
    timeBudget: 12,
    priority: "low",
    snoozed: true,
    dueDate: "2024-11-28",
    assignee: "Emma Thompson",
    taskCreator: "Sarah Chen",
    assignedDate: "2024-11-14",
    attachments: [],
    archived: false,
    subtasks: [],
  },
  {
    id: "TASK-008",
    title: "Year-End Server Maintenance",
    companyName: "TechCorp Solutions",
    projectName: "Infrastructure",
    timeSpent: 0,
    timeBudget: 16,
    priority: "high",
    snoozed: false,
    dueDate: "2024-12-30",
    assignee: "Tom Wilson",
    taskCreator: "James Kumar",
    assignedDate: null,
    attachments: [
      {
        type: "document",
        url: "https://storage.company.com/maintenance/schedule-2024.pdf",
        name: "Maintenance Schedule",
      },
    ],
    archived: false,
    subtasks: [],
  },
  {
    id: "TASK-009",
    title: "Client Presentation Preparation",
    companyName: "Global Finance Inc",
    projectName: "Client Relations",
    timeSpent: 3.5,
    timeBudget: 5,
    priority: "medium",
    snoozed: false,
    dueDate: "2024-11-22",
    assignee: "Jennifer Park",
    taskCreator: "David Wilson",
    assignedDate: "2024-11-16",
    attachments: [
      {
        type: "presentation",
        url: "https://storage.company.com/presentations/client-review-q4.pptx",
        name: "Q4 Client Review",
      },
    ],
    archived: false,
    subtasks: [
      {
        id: "ST-008",
        title: "Gather performance metrics",
        completed: true,
      },
    ],
  },
  {
    id: "TASK-010",
    title: "Employee Satisfaction Survey",
    companyName: "HR Solutions Pro",
    projectName: "Employee Engagement",
    timeSpent: 0,
    timeBudget: 6,
    priority: "none",
    snoozed: false,
    dueDate: null,
    assignee: "Robert Kim",
    taskCreator: "Maria Garcia",
    assignedDate: null,
    attachments: [],
    archived: true,
    subtasks: [],
  },
];

export type TaskData = (typeof taskData)[0];
